function timestamp() {
  const stamp =
    Date.now() - Math.floor(Math.random() * 1000 * 60 * 60 * 24 * 30);
  return new Date(stamp).toISOString();
}

export const exoticArmourPieces = [
  {
    name: "Acostas Go-Bag",
    piece: "Backpack",
    level: "Level 40",
    coreOne: "Skill Tier",
    maxCoreOneValueLevel40: "1",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Skill Haste",
    attributeOneValueLevel40: "12%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Skill Damage",
    attributeTwoValueLevel40: "10%",
    attributeTwoValueLevel30: "",
    modSlots: "1",
    exoticArmourTalent: "One in the Hand....Two in the Bag",
  },
  {
    name: "Acostas Go-Bag",
    piece: "Backpack",
    level: "World Tier 5",
    coreOne: "Skill Tier",
    maxCoreOneValueLevel40: "1",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Skill Haste",
    attributeOneValueLevel40: "12%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Skill Damage",
    attributeTwoValueLevel40: "10%",
    attributeTwoValueLevel30: "",
    modSlots: "1",
    exoticArmourTalent: "One in the Hand....Two in the Bag",
  },
  {
    name: "Memento",
    piece: "Backpack",
    level: "Level 40",
    coreOne: "Weapon Damage",
    maxCoreOneValueLevel40: "15%",
    maxCoreOneValueLevel30: "",
    coreTwo: "Armour",
    maxCoreTwoValueLevel40: "170,000",
    maxCoreTwoValueLevel30: "",
    coreThree: "+1 Skill Tier",
    maxCoreThreeValueLevel40: "1",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "",
    attributeOneValueLevel40: "",
    attributeOneValueLevel30: "",
    attributeTwoType: "",
    attributeTwoValueLevel40: "",
    attributeTwoValueLevel30: "",
    modSlots: "1",
    exoticArmourTalent: "Kill Confirmed",
  },
  {
    name: "Ridgeways Pride",
    piece: "Chest",
    level: "Level 40",
    coreOne: "Weapon Damage",
    maxCoreOneValueLevel40: "15%",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Critical Hit Chance",
    attributeOneValueLevel40: "6%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Critical Hit Damage",
    attributeTwoValueLevel40: "12%",
    attributeTwoValueLevel30: "",
    modSlots: "1",
    exoticArmourTalent: "Bleeding Edge",
  },
  {
    name: "Tardigrade Armor System",
    piece: "Chest",
    level: "Level 40",
    coreOne: "Armour",
    maxCoreOneValueLevel40: "170,000",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Explosive Resistance",
    attributeOneValueLevel40: "10%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Armour Regeneration",
    attributeTwoValueLevel40: "4,925",
    attributeTwoValueLevel30: "",
    modSlots: "1",
    exoticArmourTalent: "Ablative Nano-Plating",
  },
  {
    name: "Tardigrade Armor System",
    piece: "Chest",
    level: "World Tier 5",
    coreOne: "Armour",
    maxCoreOneValueLevel40: "",
    maxCoreOneValueLevel30: "42,458",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Explosive Resistance",
    attributeOneValueLevel40: "",
    attributeOneValueLevel30: "6.6%",
    attributeTwoType: "Armour Regeneration",
    attributeTwoValueLevel40: "",
    attributeTwoValueLevel30: "1,223",
    modSlots: "1",
    exoticArmourTalent: "Ablative Nano-Plating",
  },
  {
    name: "BTSU Datagloves",
    piece: "Gloves",
    level: "Level 40",
    coreOne: "Skill Tier",
    maxCoreOneValueLevel40: "1",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Skill Haste",
    attributeOneValueLevel40: "12%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Repair Skills",
    attributeTwoValueLevel40: "20%",
    attributeTwoValueLevel30: "",
    modSlots: "0",
    exoticArmourTalent: "Transference Overclock",
  },
  {
    name: "BTSU Datagloves",
    piece: "Gloves",
    level: "World Tier 5",
    coreOne: "Skill Tier",
    maxCoreOneValueLevel40: "1",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Skill Haste",
    attributeOneValueLevel40: "",
    attributeOneValueLevel30: "7.9%",
    attributeTwoType: "Repair Skills",
    attributeTwoValueLevel40: "",
    attributeTwoValueLevel30: "12.1%",
    modSlots: "0",
    exoticArmourTalent: "Transference Overclock",
  },
  {
    name: "Dodge City Gunslingers Holster",
    piece: "Holster",
    level: "Level 40",
    coreOne: "Weapon Damage",
    maxCoreOneValueLevel40: "15%",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Weapon Handling",
    attributeOneValueLevel40: "8%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Headshot Damage",
    attributeTwoValueLevel40: "10%",
    attributeTwoValueLevel30: "",
    modSlots: "0",
    exoticArmourTalent: "Quick Draw",
  },
  {
    name: "Dodge City Gunslingers Holster",
    piece: "Holster",
    level: "World Tier 5",
    coreOne: "Weapon Damage",
    maxCoreOneValueLevel40: "9.9%",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Weapon Handling",
    attributeOneValueLevel40: "7%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Headshot Damage",
    attributeTwoValueLevel40: "6.9%",
    attributeTwoValueLevel30: "",
    modSlots: "0",
    exoticArmourTalent: "Quick Draw",
  },
  {
    name: "Imperial Dynasty",
    piece: "Holster",
    level: "Level 40",
    coreOne: "Skill Tier",
    maxCoreOneValueLevel40: "1",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Status Effect",
    attributeOneValueLevel40: "10%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Hazard Protection",
    attributeTwoValueLevel40: "10%",
    attributeTwoValueLevel30: "",
    modSlots: "0",
    exoticArmourTalent: "Dragons Glare",
  },
  {
    name: "Imperial Dynasty",
    piece: "Holster",
    level: "World Tier 5",
    coreOne: "Skill Tier",
    maxCoreOneValueLevel40: "1",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Status Effect",
    attributeOneValueLevel40: "",
    attributeOneValueLevel30: "6.6%",
    attributeTwoType: "Hazard Protection",
    attributeTwoValueLevel40: "",
    attributeTwoValueLevel30: "6.6%",
    modSlots: "0",
    exoticArmourTalent: "Dragons Glare",
  },
  {
    name: "Waveform",
    piece: "Holster",
    level: "Level 40",
    coreOne: "Skill Tier",
    maxCoreOneValueLevel40: "1",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Skill Damage",
    attributeOneValueLevel40: "10%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Skill Haste",
    attributeTwoValueLevel40: "12%",
    attributeTwoValueLevel30: "",
    modSlots: "0",
    exoticArmourTalent: "Alternating Current",
  },
  {
    name: "NinjaBike Messenger Kneepads",
    piece: "Kneepads",
    level: "Level 40",
    coreOne: "Weapon Damage",
    maxCoreOneValueLevel40: "",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Critical Hit Chance",
    attributeOneValueLevel40: "6%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Critical Hit Damage",
    attributeTwoValueLevel40: "12%",
    attributeTwoValueLevel30: "",
    modSlots: "0",
    exoticArmourTalent: "Parkour!",
  },
  {
    name: "NinjaBike Messenger Kneepads",
    piece: "Kneepads",
    level: "World Tier 5",
    coreOne: "Weapon Damage",
    maxCoreOneValueLevel40: "",
    maxCoreOneValueLevel30: "9.9%",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Critical Hit Chance",
    attributeOneValueLevel40: "",
    attributeOneValueLevel30: "5.1%",
    attributeTwoType: "Critical Hit Damage",
    attributeTwoValueLevel40: "",
    attributeTwoValueLevel30: "7.9%",
    modSlots: "0",
    exoticArmourTalent: "Parkour!",
  },
  {
    name: "Sawyers Kneepads",
    piece: "Kneepads",
    level: "Level 40",
    coreOne: "Armour",
    maxCoreOneValueLevel40: "170,000",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Explosive Resistance",
    attributeOneValueLevel40: "10%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Health",
    attributeTwoValueLevel40: "18,935",
    attributeTwoValueLevel30: "",
    modSlots: "0",
    exoticArmourTalent: "Stand Your Ground",
  },
  {
    name: "Sawyers Kneepads",
    piece: "Kneepads",
    level: "World Tier 5",
    coreOne: "Armour",
    maxCoreOneValueLevel40: "",
    maxCoreOneValueLevel30: "42,458",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Explosive Resistance",
    attributeOneValueLevel40: "6.6%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Health",
    attributeTwoValueLevel40: "",
    attributeTwoValueLevel30: "4,695",
    modSlots: "0",
    exoticArmourTalent: "Stand Your Ground",
  },
  {
    name: "Coyote Mask",
    piece: "Mask",
    level: "Level 40",
    coreOne: "Weapon Damage",
    maxCoreOneValueLevel40: "15%",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Critical Hit Chance",
    attributeOneValueLevel40: "6%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Critical Hit Damage",
    attributeTwoValueLevel40: "12%",
    attributeTwoValueLevel30: "",
    modSlots: "1",
    exoticArmourTalent: "Pack Instincts",
  },
  {
    name: "Vile",
    piece: "Mask",
    level: "Level 40",
    coreOne: "Skill Tier",
    maxCoreOneValueLevel40: "1",
    maxCoreOneValueLevel30: "",
    coreTwo: "",
    maxCoreTwoValueLevel40: "",
    maxCoreTwoValueLevel30: "",
    coreThree: "",
    maxCoreThreeValueLevel40: "",
    maxCoreThreeValueLevel30: "",
    attributeOneType: "Status Effect",
    attributeOneValueLevel40: "10%",
    attributeOneValueLevel30: "",
    attributeTwoType: "Hazard Protection",
    attributeTwoValueLevel40: "10%",
    attributeTwoValueLevel30: "",
    modSlots: "1",
    exoticArmourTalent: "Toxic Delivery",
  },
];
