function timestamp() {
  const stamp =
    Date.now() - Math.floor(Math.random() * 1000 * 60 * 60 * 24 * 30);
  return new Date(stamp).toISOString();
}

export const weaponTalents = [
  {
    name: "Boomerang",
    type: "Weapon DPS",
    descriptionPVE:
      "Critical hits have a 50% chance to return the bullet to the magazine. If a bullet is returned to the magazine, the next shot has 40% increased damage.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: true,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "NO",
    isExotic: "NO",
    weaponName: "",
  },
  {
    name: "Perfect Boomerang",
    type: "Weapon DPS",
    descriptionPVE:
      "Critical hits have a 75% chance to return the bullet to the magazine. If a bullet is returned to the magazine, the next shot has 50% increased damage.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: true,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "NO",
    weaponName: "",
  },
  {
    name: "Breadbasket",
    type: "Weapon DPS",
    descriptionPVE:
      "Landing body shots adds a stack of bonus 35% headshot damage to the next headshot for 10 seconds. Max stack is 3.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Breadbasket",
    type: "Weapon DPS",
    descriptionPVE:
      "Landing body shots adds a stack of bonus 50% headshot damage to the next headshot for 10 seconds. Max stack is 2.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: true,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Close & Personal",
    type: "Weapon DPS",
    descriptionPVE:
      "Killing a target within 7 meters grants 30% weapon damage for 10 seconds.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfectly Close & Personal",
    type: "Weapon DPS",
    descriptionPVE:
      "Killing a target within 7 meters grants 38% weapon damage for 10 seconds.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Eyeless",
    type: "Weapon DPS",
    descriptionPVE:
      "Deal 20% weapon damage to blinded enemies. After 4 kills, applies blind to the next enemy you hit.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Eyeless",
    type: "Weapon DPS",
    descriptionPVE:
      "Deal 20% weapon damage to blinded enemies. After 4 kills, applies blind to the next enemy you hit.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: true,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Fast Hands",
    type: "Weapon Utility",
    descriptionPVE:
      "Critical hits add a stack of 4% reload speed bonus. Max stack is 40.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Fast Hands",
    type: "Weapon Utility",
    descriptionPVE:
      "Critical hits add a stack of 8% reload speed bonus. Max stack is 40.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: true,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Finisher",
    type: "Weapon DPS",
    descriptionPVE:
      "Swapping from this weapon within 10 seconds of killing an enemy grants 30% critical hit chance and 30% critical hit damage for 15 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: true,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Finisher",
    type: "Weapon DPS",
    descriptionPVE:
      "Swapping from this weapon within 10 seconds of killing an enemy grants 35% critical hit chance and 40% critical hit damage for 15 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: true,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "First Blood",
    type: "Weapon Utility",
    descriptionPVE:
      "If scoped, your first shot fired from out of combat or after fully reloading from empty deals headshot damage to any part of the body hit. Requires a Scope with 8x magnification or higher.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: true,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect First Blood",
    type: "Weapon Utility",
    descriptionPVE:
      "If scoped, your first 2 shots fired from out of combat or after fully reloading from empty deals headshot damage to any part of the body hit. Requires a Scope with 8x magnification or higher.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: true,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Frenzy",
    type: "Weapon DPS",
    descriptionPVE:
      "For every 10 bullets in the magazine capacity, gain 3% rate of fire and 3% weapon damage for 5 seconds when reloading from empty.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: true,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Frenzy",
    type: "Weapon DPS",
    descriptionPVE:
      "For every 8 bullets in the magazine capacity, gain 3% rate of fire and 3% weapon damage for 5 seconds when reloading from empty.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: true,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Future Perfect",
    type: "Skill",
    descriptionPVE:
      "Weapon kills grant 1 skill tier for 15 seconds. Stacks up to 3 times. Weapon Kill at tier 6 grant overcharge for 15 seconds. Overcharge cooldown is 90 seconds.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Future Perfection",
    type: "Skill",
    descriptionPVE:
      "Weapon kills grant 1 skill tier for 19 seconds. Stacks up to 3 times. Weapon Kill at tier 6 grant overcharge for 15 seconds. Overcharge cooldown is 90 seconds.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: true,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Ignited",
    type: "Weapon DPS",
    descriptionPVE:
      "Deal 20% weapon damage to burning enemies. After 4 kills, applies burning to the next enemy you hit.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfectly Ignited",
    type: "Weapon DPS",
    descriptionPVE:
      "Deal 25% weapon damage to burning enemies. After 3 kills, applies burning to the next enemy you hit.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "In Sync",
    type: "Hybrid",
    descriptionPVE:
      "Hitting an enemy grants 15% skill damage for 5 seconds. Using a skill or damaging an enemy with a skill grants 15% weapon damage for 5 seconds. Damage increases are doubled while both buffs are active at the same time.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfectly In Sync",
    type: "Hybrid",
    descriptionPVE:
      "Hitting an enemy grants 20% skill damage for 5 seconds. Using a skill or damaging an enemy with a skill grants 20% weapon damage for 5 seconds. Damage increases are doubled while both buffs are active at the same time.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: true,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Killer",
    type: "Weapon DPS",
    descriptionPVE:
      "Killing an enemy with a critical hit grants 40% critical hit damage for 10 seconds.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Killer",
    type: "Weapon DPS",
    descriptionPVE:
      "Killing an enemy with a critical hit grants 40% critical hit damage for 10 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: true,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Lucky Shot",
    type: "Weapon Utility",
    descriptionPVE:
      "Magazine capacity is increased by 20%. Missed shots from cover have a 100% chance to return to the magazine.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Lucky Shot",
    type: "Weapon Utility",
    descriptionPVE:
      "Magazine capacity is increased by 30%. Missed shots from cover have a 100% chance to return to the magazine.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: true,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Measured",
    type: "Weapon DPS",
    descriptionPVE:
      "The top half of the magazine has +20% rate of fire and -30% weapon damage. The bottom half of the magazine has -20% rate of fire and +30% total weapon damage.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfectly Measured",
    type: "Weapon DPS",
    descriptionPVE:
      "The top half of the magazine has +20% rate of fire and -27% weapon damage. The bottom half of the magazine has -20% rate of fire and +33% total weapon damage.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: true,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Naked",
    type: "Weapon DPS",
    descriptionPVE:
      "Hitting an enemy with no armor grants 50% headshot damage for 5 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: true,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfectly Naked",
    type: "Weapon DPS",
    descriptionPVE:
      "Hitting an enemy with no armor grants 50% headshot damage for 8 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: true,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Near Sighted",
    type: "Weapon Utility",
    descriptionPVE: "Receive 80% stability at the cost of 35% optimal range.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Near Sighted",
    type: "Weapon Utility",
    descriptionPVE: "Receive 100% stability at the cost of 35% optimal range.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "On Empty",
    type: "Weapon Utility",
    descriptionPVE:
      "Reloading from empty grants 30% weapon handling for 10 seconds.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect On Empty",
    type: "Weapon Utility",
    descriptionPVE:
      "Reloading from empty grants 30% weapon handling for 10 seconds.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Optimist",
    type: "Weapon DPS",
    descriptionPVE:
      "Weapon damage is increased by 3% for every 10% ammo missing from the magazine.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Optimist",
    type: "Weapon DPS",
    descriptionPVE:
      "Weapon damage is increased by 3% for every 10% ammo missing from the magazine.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Outsider",
    type: "Weapon Utility",
    descriptionPVE:
      "After killing an enemy, gain 100% optimal range and 100% accuracy for 10 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Outsider",
    type: "Weapon Utility",
    descriptionPVE:
      "After killing an enemy, gain 100% optimal range and 100% accuracy for 10 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: true,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Overflowing",
    type: "Weapon Utility",
    descriptionPVE:
      "Every 3 reloads from empty increases your base magazine capacity by 100%.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Overflowing",
    type: "Weapon Utility",
    descriptionPVE:
      "Every 3 reloads from empty increases your base magazine capacity by 100%.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Overwhelm",
    type: "Weapon DPS",
    descriptionPVE:
      "Suppressing an enemy, that is not currently suppressed, grants 10% weapon damage for 12 seconds. Max stack is 4.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: true,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Overwhelm",
    type: "Weapon DPS",
    descriptionPVE:
      "Suppressing an enemy, that is not currently suppressed, grants 12% weapon damage for 12 seconds. Max stack is 4.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: true,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perpetuation",
    type: "Status",
    descriptionPVE:
      "Headshots grant 50% status effect damage and duration to the next status effect you apply. Cooldown is 20 seconds.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Perpetuation",
    type: "Status",
    descriptionPVE:
      "Headshots grant 50% status effect damage and duration to the next status effect you apply. Cooldown is 16 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: true,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Preservation",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Killing an enemy repairs 10% armor over 5 seconds. Headshot kills improves the repair to 20%.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Preservation",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Killing an enemy repairs 10% armor over 5 seconds. Headshot kills improves the repair to 20%.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Pummel",
    type: "Weapon DPS",
    descriptionPVE:
      "3 consecutive kills refill the magainze and grant 40% weapon damage for 10 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: true,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Pummel",
    type: "Weapon DPS",
    descriptionPVE:
      "2 consecutive kills refill the magainze and grant 40% weapon damage for 10 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: true,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Pumped Up",
    type: "Weappon DPS",
    descriptionPVE:
      "Reloading grants 1% weapon damage for 10 seconds. Stacks up to 25.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: true,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Pumped Up",
    type: "Weappon DPS",
    descriptionPVE:
      "Reloading grants 5% weapon damage for 10 seconds. Stacks up to 5.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: true,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Ranger",
    type: "Weapon DPS",
    descriptionPVE:
      "Amplifies weapon damage by 2% for every 5 meters you are away from your target.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Ranger",
    type: "Weapon DPS",
    descriptionPVE:
      "Amplifies weapon damage by 2% for every 4 meters you are away from your target.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: true,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Reformation",
    type: "Heal & Support",
    descriptionPVE: "Headshots grant 30% skill repair for 15 seconds.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Reformation",
    type: "Heal & Support",
    descriptionPVE: "Headshots grant 40% skill repair for 8 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: true,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Rifleman",
    type: "Weapon DPS",
    descriptionPVE:
      "Landing headshots adds a stack of bonus 10% weapon damage for 5 seconds. Max stack is 5. Additional headshots refresh the duration.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: true,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Rifleman",
    type: "Weapon DPS",
    descriptionPVE:
      "Landing headshots adds a stack of bonus 11% weapon damage for 5 seconds. Max stack is 6. Additional headshots refresh the duration.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: true,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Sadist",
    type: "Weapon DPS",
    descriptionPVE:
      "Deal 20% weapon damage to bleeding enemies. After 4 kills, applies bleed to next enemy you hit.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Sadist",
    type: "Weapon DPS",
    descriptionPVE:
      "Deal 20% weapon damage to bleeding enemies. After 4 kills, applies bleed to next enemy you hit.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Salvage",
    type: "Weapon Utility",
    descriptionPVE: "Killing a target has a 70% chance to refill the magazine.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: true,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Salvage",
    type: "Weapon Utility",
    descriptionPVE: "Killing a target has a 85% chance to refill the magazine.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: true,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Spike",
    type: "Skill DPS",
    descriptionPVE: "Headshots grant 20% skill damage for 15 seconds.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Spike",
    type: "Skill DPS",
    descriptionPVE: "Headshots grant 20% skill damage for 15 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Steady Handed",
    type: "Weapon Utility",
    descriptionPVE:
      "Hits grant a stack of 1% accuracy and stability. At 100 stacks, consumes them to refill the magazine.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Steady Handed",
    type: "Weapon Utility",
    descriptionPVE:
      "Hits grant a stack of 1% accuracy and stability. At 75 stacks, consumes them to refill the magazine.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: true,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Strained",
    type: "Weapon DPS",
    descriptionPVE:
      "Gain 10% critical hit damage for every 0.5 seconds you are firing. Stacks up to 5 times.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfectly Strained",
    type: "Weapon DPS",
    descriptionPVE:
      "Gain 10% critical hit damage for every 0.5 seconds you are firing. Stacks up to 8 times.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Unhinged",
    type: "Weapon DPS",
    descriptionPVE:
      "Receive 18% weapon damage at the cost of 25% stability and 25% accuracy.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: true,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Unhinged",
    type: "Weapon DPS",
    descriptionPVE:
      "Receive 22% weapon damage at the cost of 25% stability and 25% accuracy.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: true,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: false,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Unwavering",
    type: "Weapon Utility",
    descriptionPVE:
      "Swapping to this weapon grants 300% weapon handling for 5 seconds. Kills refresh the buff. Swapping away disables this from all weapons for 5 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Unwavering",
    type: "Weapon Utility",
    descriptionPVE:
      "Swapping to this weapon grants 400% weapon handling for 5 seconds. Kills refresh the buff. Swapping away disables this from all weapons for 5 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: true,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Vindictive",
    type: "Weapon DPS",
    descriptionPVE:
      "Killing an enemy with a status effect applied grants all group members within 15 meters, 15% critical hit chance and 15% critical hit damage for 20 seconds.",
    descriptionPVP: "",
    classARTalent: true,
    classLMGTalent: true,
    classMMRTalent: true,
    classPistolTalent: true,
    classRifleTalent: true,
    classShotgunTalent: true,
    classSMGTalent: true,
    isNamed: "",
    isExotic: "",
    weaponName: "",
  },
  {
    name: "Perfect Vindictive",
    type: "Weapon DPS",
    descriptionPVE:
      "Killing an enemy with a status effect applied grants all group members within 20 meters, 18% critical hit chance and 18% critical hit damage for 20 seconds.",
    descriptionPVP: "",
    classARTalent: false,
    classLMGTalent: false,
    classMMRTalent: false,
    classPistolTalent: false,
    classRifleTalent: false,
    classShotgunTalent: false,
    classSMGTalent: true,
    isNamed: "YES",
    isExotic: "",
    weaponName: "",
  },
];
