function timestamp() {
  const stamp =
    Date.now() - Math.floor(Math.random() * 1000 * 60 * 60 * 24 * 30);
  return new Date(stamp).toISOString();
}

export const armourTalents = [
  {
    name: "Braced",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE: "While in cover weapon handling is increased by 45%",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Braced",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE:
      "Perfect Braced: While in cover weapon handling is increased by 50%.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Vedmedytsya Vest - Brand: Petrov",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Focus",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE:
      "Increases total weapon damage by 5% every second you are aiming while scoped 8x or higher, up to 50%.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Focus",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE:
      "Increases total weapon damage by 5% every second you are aiming while scoped 8x or higher, up to 60%.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Pristine Example - Brand: Airaldi Holdings",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Glass Cannon",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE:
      "All damage you deal is amplified by 25%. All damage you take is amplified by 50%",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Glass Cannon",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE:
      "All damage you deal is amplified by 30%. All damage you take is amplified by 60%",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "The Sacrifice - Brand: Providence Defence",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Gunslinger",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE:
      "Weapon swapping increases total weapon damage by 20% for 5 seconds. This buff is lost for 5 seconds if you weapon swap while it is active.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Headhunter",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE:
      "After killing an enemy with a headshot, your next weapon hit within 30 seconds deals an additional 125% fo that killing blow's damage. Damage is capped at 800% of your weapon damage. This is raised to 1250% if your headshot damage is greater than 150%.",
    descriptionPVP:
      "After killing an enemy with a headshot, your next weapon hit within 5 seconds deals an additional 20% fo that killing blow's damage. Damage is capped at 200% of your weapon damage. This is raised to 300% if your headshot damage is greater than 150%.",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Headhunter",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE:
      "Perfect Headhunter: After killing an enemy with a headshot, your next weapon hit within 30 seconds deals an additional 150% fo that killing blow's damage. Damage is capped at 800% of your weapon damage. This is raised to 1250% if your headshot damage is greater than 150%.",
    descriptionPVP:
      "Perfect Headhunter: After killing an enemy with a headshot, your next weapon hit within 5 seconds deals an additional 25% fo that killing blow's damage. Damage is capped at 200% of your weapon damage. This is raised to 300% if your headshot damage is greater than 150%",
    isNamed: "YES",
    namedItem: "Chainkiller - Brand: Walker, Harris & Co.",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Obliterate",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE:
      "Critical hits increase total weapon damage by 1% for 5 seconds. Stacks up to 25 times.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Spark",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE:
      "Damaging an enemy with a skill increases total weapon damage by 15% for 15 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Spark",
    piece: "Chest",
    type: "Weapon DPS",
    descriptionPVE:
      "Damaging an enemy with a skill increases total weapon damage by 15% for 20 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "Door-Kickers Knock - Grupo Sombra S.A.",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Vanguard",
    piece: "Chest",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Deploying a shield makes it invulnerable for 5 seconds and grants 45% of your armor as bonus armor to all other allies for 20 seconds. Cooldown is 25 seconds.",
    descriptionPVP:
      "Deploying a shield makes it invulnerable for 2 seconds and grants 20% of your armor as bonus armor to all other allies for 20 seconds. Cooldown is 25 seconds.",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Vanguard",
    piece: "Chest",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Deploying a shield makes it invulnerable for 5 seconds and grants 50% of your armor as bonus armor to all other allies for 20 seconds. Cooldown is 25 seconds.",
    descriptionPVP:
      "Deploying a shield makes it invulnerable for 2 seconds and grants 25% of your armor as bonus armor to all other allies for 20 seconds. Cooldown is 25 seconds.",
    isNamed: "YES",
    namedItem: "Pointman - Brand: Gila Guard",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Unbreakable",
    piece: "Chest",
    type: "Tank & Bruiser",
    descriptionPVE:
      "When your armor is depleted, repair 95% of your armor. Cooldown is 60 seconds.",
    descriptionPVP:
      "When your armor is depleted, repair 50% of your armor. Cooldown is 60 seconds.",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfectly Unbreakable",
    piece: "Chest",
    type: "Tank & Bruiser",
    descriptionPVE:
      "When your armor is depleted, repair 100% of your armor. Cooldown is 55 seconds.",
    descriptionPVP:
      "When your armor is depleted, repair 55% of your armor. Cooldown is 55 seconds.",
    isNamed: "YES",
    namedItem: "Zero Fs - Brand: Badger Tuff",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Protected Reload",
    piece: "Chest",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Grants 20% bonus armor while reloading. Grants 0-18% of your armor as bonus armor to all other allies when they are reloading, based on your [defence] core attribute.",
    descriptionPVP:
      "Grants 15% bonus armor while reloading. Grants 0-12% of your armor as bonus armor to all other allies when they are reloading, based on your [defence] core attribute.",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Intimidate",
    piece: "Chest",
    type: "Tank & Bruiser",
    descriptionPVE:
      "While you have bonus armor, amplifies total weapon damage by 35% to enemies within 10 meters.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Intimidate",
    piece: "Chest",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Perfect Intimidate: While you have bonus armor, amplifies total weapon damage by 40% to enemies within 10 meters.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Hunter-Killer - Brand: Golan Gear",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Entrench",
    piece: "Chest",
    type: "Tank & Bruiser",
    descriptionPVE:
      "If you are below 30% armor, headshots from cover repair 20% of your armor. Cooldown is 6 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Efficient",
    piece: "Chest",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Using an armor kit has a 50% chance to not consume the armor kit. Specialization armor kit bonuses are increased by 100%.",
    descriptionPVP:
      "Using an armor kit has a 50% chance to not consume the armor kit. Specialization armor kit bonuses are increased by 50%.",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfectly Efficient",
    piece: "Chest",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Using an armor kit has a 75% chance to not consume the armor kit. Specialization armor kit bonuses are increased by 100%.",
    descriptionPVP:
      "Using an armor kit has a 75% chance to not consume the armor kit. Specialization armor kit bonuses are increased by 50%.",
    isNamed: "YES",
    namedItem: "Everyday Carrier - Brand: Belstone Armory",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Tamper Proof",
    piece: "Chest",
    type: "Skill DPS",
    descriptionPVE:
      "Enemies that walk within 3 meters of your hive, turret, or remote pulse are shocked. Arm time is 3 seconds and cooldown per skill is 10 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Tag Team",
    piece: "Chest",
    type: "Skill DPS",
    descriptionPVE:
      "The last enemy you have damaged with a skill is marked. Dealing weapon damage to that enemy consumes the mark to reduce active cooldowns by 6 seconds. Cooldown: 4 seconds",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Spotter",
    piece: "Chest",
    type: "Skill DPS",
    descriptionPVE:
      "Amplifies total weapon and skill damage by 15% to pulsed enemies.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Skilled",
    piece: "Chest",
    type: "Skill DPS",
    descriptionPVE:
      "Skill kills have a 25% chance to reset skill cooldowns. If no skills were on cooldown, you instead gain one-time buff that immediately refreshes a skill's cooldown when it goes on cooldown.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfectly Skilled",
    piece: "Chest",
    type: "Skill DPS",
    descriptionPVE:
      "Skill kills have a 30% chance to reset skill cooldowns. If no skills were on cooldown, you instead gain one-time buff that immediately refreshes a skill's cooldown when it goes on cooldown.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Caesar's Guard - Brand: Empress International",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Kinetic Momentum",
    piece: "Chest",
    type: "Skill DPS",
    descriptionPVE:
      "When in combat, each skill generates a stack while active or not on cooldown. Stacks increase your total skill damage by 1% and total skill repair by 2%. Up to 15 stacks per skill. Lost when on cooldown.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Explosive Delivery",
    piece: "Chest",
    type: "Skill DPS",
    descriptionPVE:
      "Whenever you throw a skill, 1.5 seconds after landing, it creates an explosion damaging enemies within 5 meters. Damage scales with skill tier dealing 25-100% damage of a concussion grenade. At most once per skill. Remote Pulse, All Turrets, All Hives, Explosive Seeker, Cluster Seeker, Mender Seeker, Decoy, All Traps.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Trauma",
    piece: "Chest",
    type: "Heal & Support",
    descriptionPVE:
      "Applies blind to an enemy hit in the head. Cooldown is 30 seconds. Applies bleed to an enemy hit in the Chest. Cooldown is 30 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Reassigned",
    piece: "Chest",
    type: "Heal & Support",
    descriptionPVE:
      "Killing an enemy adds 1 round of a random special ammo into your sidearm. Cooldown is 20 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Overwatch",
    piece: "Chest",
    type: "Heal & Support",
    descriptionPVE:
      "After staying in cover for 10 seconds, increase your and all allies total weapon and skill damage by 12% as long as you remain in cover or in a cover-to-cover move.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Overwatch",
    piece: "Chest",
    type: "Heal & Support",
    descriptionPVE:
      "After staying in cover for 8 seconds, increase your and all allies total weapon and skill damage by 12% as long as you remain in cover or in a cover-to-cover move.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Ferocious Calm - Brand: Fenris Group AB",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Mad Bomber",
    piece: "Chest",
    type: "Heal & Support",
    descriptionPVE:
      'Grenade radius is increased by 50%. Grenades that kill an enemy are refunded. Grenades can now be "cooked" by holding the fire button, making them explode earlier. Gain 15% bonus armor while aiming grenades.',
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Empathic Resolve",
    piece: "Chest",
    type: "Heal & Support",
    descriptionPVE:
      "Repairing an ally, increases their total weapon and skill damage by 3-15% for 20 seconds. 1-7% if self. Effectiveness increased by your skill tier.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Vigilance",
    piece: "Backpack",
    type: "Weapon DPS",
    descriptionPVE:
      "Increases total weapon damage by 25%. Taking damage disables this buff for 4 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Vigilance",
    piece: "Backpack",
    type: "Weapon DPS",
    descriptionPVE:
      "Increases total weapon damage by 25%. Taking damage disables this buff for 3 seconds.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "The Gift - Brand: Providence Defence",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Versatile",
    piece: "Backpack",
    type: "Weapon DPS",
    descriptionPVE:
      "Amplifies total weapon damage for 10 seconds when swapping between your primary and secondary weapons if they are different. 35% to enemies within 15 meters for Shotguns and SMGs. 35% to enemies further than 25 meters for Rifles and Marksman Rifles. 10% to enemies between 15 - 25 meters for LMGs and Assault Rifles. At most once per 5 seconds per weapon type.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Unstoppable Force",
    piece: "Backpack",
    type: "Weapon DPS",
    descriptionPVE:
      "Killing an enemy increases total weapon damage by 5% for 15 seconds. Stacks up to 5 times.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Opportunistic",
    piece: "Backpack",
    type: "Weapon DPS",
    descriptionPVE:
      "Enemies you hit with shotguns and marksman rifles amplifies the damage they take by 10% from all sources for 5 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Concussion",
    piece: "Backpack",
    type: "Weapon DPS",
    descriptionPVE:
      "Headshots increase total weapon damage by 10% for 1.5 seconds. 5 seconds with marksman rifles. Headshot kills additionally increase total weapon damage by 15% for 10 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Composure",
    piece: "Backpack",
    type: "Weapon DPS",
    descriptionPVE: "While in cover, increases total weapon damage by 15%.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Companion",
    piece: "Backpack",
    type: "Weapon DPS",
    descriptionPVE:
      "While you are within 5 meters of an ally or skill, total weapon damage is increased by 15%.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Protector",
    piece: "Backpack",
    type: "Tank & Bruiser",
    descriptionPVE:
      "When your shield is damaged, you gain 5% and all other allies gain 15% of your armor as bonus armor for 3 seconds. Cooldown is 3 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Leadership",
    piece: "Backpack",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Performing a cover to cover grants 15% of your armor as bonus armor to you and all allies for 10 seconds. This is doubled if you end within 10 meters of an enemy. Cooldown is 10 seconds.",
    descriptionPVP:
      "Performing a cover to cover grants 10% of your armor as bonus armor to you and all allies for 10 seconds. This is doubled if you end within 10 meters of an enemy. Cooldown is 10 seconds.",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Bloodsucker ",
    piece: "Backpack",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Killing an enemy adds and refreshes a stack of 10% bonus armor for 10 seconds. Max stack is 10.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Bloodsucker",
    piece: "Backpack",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Killing an enemy adds and refreshes a stack of 12% bonus armor for 10 seconds. Max stack is 10",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Liquid Engineer - Brand: Belstone Armory",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Adrenaline Rush",
    piece: "Backpack",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Whenever you are within 10 meters of an enemy, gain 20% bonus armor for 5 seconds. Stacks up to 3 times. Cooldown: 5 seconds.",
    descriptionPVP:
      "Whenever you are within 10 meters of an enemy, gain 10% bonus armor for 5 seconds. Stacks up to 3 times. Cooldown: 5 seconds.",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Adrenaline Rush",
    piece: "Backpack",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Whenever you are within 10 meters of an enemy, gain 23% bonus armor for 5 seconds. Stacks up to 3 times. Cooldown: 5 seconds.",
    descriptionPVP:
      "Whenever you are within 10 meters of an enemy, gain 12% bonus armor for 5 seconds. Stacks up to 3 times. Cooldown: 5 seconds.",
    isNamed: "YES",
    namedItem: "Matador - Brand: Walker, Harris & Co.",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Clutch",
    piece: "Backpack",
    type: "Sustain",
    descriptionPVE:
      "If you are below 15% armor, critical hits repair 2.5% missing armor. Kills allow you to repair up to 100% armor for 4-10 seconds, based on your [Weapon] core attribute.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Clutch",
    piece: "Backpack",
    type: "Sustain",
    descriptionPVE:
      "If you are below 20% armor, critical hits repair 2.5% missing armor. Kills allow you to repair up to 100% armor for 4-10 seconds, based on your [Weapon] core attribute.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Devils Due - Brand: Ceska Vyroba s.r.o.",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Wicked",
    piece: "Backpack",
    type: "Status",
    descriptionPVE:
      "Applying a Status effect increases total weapon damage by 18% for 20 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfectly Wicked",
    piece: "Backpack",
    type: "Status",
    descriptionPVE:
      "Applying a Status effect increases total weapon damage by 18% for 27 seconds.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Anarchists Cookbook - Brand: Golan Gear",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Galvanize",
    piece: "Backpack",
    type: "Status",
    descriptionPVE:
      "Applying a Blind, Ensnare, Confuse, or Shock to an enemy grants 40% of your armor as bonus armor to you and all allies within 20 meters of that enemy for 10 seconds.",
    descriptionPVP:
      "Applying a Blind, Ensnare, Confuse, or Shock to an enemy grants 20% of your armor as bonus armor to you and all allies within 20 meters of that enemy for 10 seconds.",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Creeping Death",
    piece: "Backpack",
    type: "Status",
    descriptionPVE:
      "When you apply a Status effect, it is also applied to all enemies within 8 meters of your target. Cooldown is 15 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Tech Support",
    piece: "Backpack",
    type: "Skill DPS",
    descriptionPVE:
      "Skill kills increase total skill damage by 25% for 20 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Tech Support",
    piece: "Backpack",
    type: "Skill DPS",
    descriptionPVE:
      "Skill kills increase total skill damage by 25% for 27 seconds.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Percussive Maintenance - Brand: Alps Summit Armament",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Shock and Awe",
    piece: "Backpack",
    type: "Skill DPS",
    descriptionPVE:
      "Applying a Status effect to an enemy increases total skill damage and repair by 20% for 20 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Shock and Awe",
    piece: "Backpack",
    type: "Skill DPS",
    descriptionPVE:
      "Applying a Status effect to an enemy increases total skill damage and repair by 20% for 27 seconds.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Strategic Alignment - Brand: China Light Industries",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Combined Arms",
    piece: "Backpack",
    type: "Skill DPS",
    descriptionPVE:
      "Shooting an enemy increases total skill damage by 25% for 3 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfect Combined Arms",
    piece: "Backpack",
    type: "Skill DPS",
    descriptionPVE:
      "Shooting an enemy increases total skill damage by 30% for 3 seconds.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Force Multiplier - Brand: Hana-U Corporation",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Calculated",
    piece: "Backpack",
    type: "Skill DPS",
    descriptionPVE: "Kills from cover reduce skill cooldowns by 10%.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Perfectly Calculated",
    piece: "Backpack",
    type: "Skill DPS",
    descriptionPVE: "Kills from cover reduce skill cooldowns by 15%.",
    descriptionPVP: "",
    isNamed: "YES",
    namedItem: "Battery Pack - Brand: Empress International",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Safeguard",
    piece: "Backpack",
    type: "Heal & Support",
    descriptionPVE:
      "While at full armor, increases total skill repair by 100%.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "Overclock",
    piece: "Backpack",
    type: "Heal & Support",
    descriptionPVE:
      "You and allies within 7 meters of your deployed skills, gain 25% reload speed and reduces active cooldowns by 0.2s each second.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
  {
    name: "One in the Hand....Two in the Bag",
    piece: "Backpack",
    type: "Heal & Support",
    descriptionPVE:
      "One in Hand...Throwing a grenade refunds it and grants +1 skill tier for 15 seconds. Grants overcharge if already at skill tier 6. Cooldown is 60 seconds. ... Two in the Bag +1 Armor Kit Capacity, +3 Grenade Capacity, +25% Ammo Capacity, +10% Skill Repair, +10% Status Effects",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "Acostas Go-Bag",
  },
  {
    name: "Kill Confirmed",
    piece: "Backpack",
    type: "Sustain",
    descriptionPVE:
      "Enemies you kill drop a trophy on death. Collecting trophies provides both a short- and long - term buff, the first of which scales with the number of core attributes equipped and lasts 10 seconds. 5 % weapon damage per red core, 10 % bonus armor per blue core. 5 % skill efficiency per yellow core.For every trophy collected, gain an additional + 1 % weapon damage, +1 % skill efficiency, and + 0.1 % armor regeneration for 300s.Maximum 30 stacks.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "Memento",
  },
  {
    name: "Bleeding Edge",
    piece: "Chest",
    type: "Sustain",
    descriptionPVE:
      "Shooting enemies within 15 meters applies bleed to the target. Repair 3-48% of your armor per second for every enemy that is bleeding within 10 meters. 1 enemy: 3%, 2 enemies: 6%, 3 enemies: 12%, 4 enemies: 24%, 5 enemies: 48%",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "Ridgeways Pride",
  },
  {
    name: "Ablative Nano-Plating",
    piece: "Chest",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Whenever your or any ally's armor breaks, they gain 80% of your armor as bonus armor> for 10 seconds. Cooldown per ally: 45 seconds. Killing an enemy with your specialization weapon removes this cooldown for all allies.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "Tardigrade Armour System",
  },
  {
    name: "Transference Overclock",
    piece: "Gloves",
    type: "Heal & Support",
    descriptionPVE:
      "Grants +15% hive skill haste per skill tier. Detonating a Hive refreshes your skill cooldowns and grants overcharge for 15 seconds. If at skill tier 6, this effect also applies to all allies. Allies receiving this effect are unable to benefit from it again for 120 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "BTSU Datagloves",
  },
  {
    name: "Quick Draw",
    piece: "Holster",
    type: "Weapon DPS",
    descriptionPVE:
      "While your pistol is holstered, gain a stacking buff every 0.3 seconds, up to 100. When you swap to it, your first shot consumes the buff and deals +10% damage per stack. This deals headshot damage to anywhere you hit. Requires Pistol Equipped",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "Dodge City Holster",
  },
  {
    name: "Dragons Glare",
    piece: "Holster",
    type: "Status",
    descriptionPVE:
      "While in combat, applies burn to the enemy closest to you within 20 meters. Cooldown: 40 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "Imperial Dynasty",
  },
  {
    name: "Alternating Current",
    piece: "Holster",
    type: "Skill DPS",
    descriptionPVE:
      "Generate a stack of 3% Skill Damage on one of your skills every second, capping at 10 stacks. After 10 seconds at the cap the stacks transfer to your other skill. The process then repeats ad-infinitum.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "Waveform",
  },
  {
    name: "Parkour!",
    piece: "Kneepads",
    type: "Tank & Bruiser",
    descriptionPVE:
      "Performing a cover to cover or vaulting reloads your drawn weapon and grants +25% bonus armor for 5 seconds.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "",
  },
  {
    name: "Stand Your Ground",
    piece: "Kneepads",
    type: "Weapon DPS",
    descriptionPVE:
      "Cannot be staggered by explosions. Increase total weapon damage by 3% each second you are not moving. Stacks up to 10 times until you start moving. All stacks are lost 10 seconds after moving.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "Sawyers Kneepads",
  },
  {
    name: "Pack Instincts",
    piece: "Mask",
    type: "Weapon DPS",
    descriptionPVE:
      "You and all allies gain a bonus based on the distance of the last enemy you hit. 0 - 15 meters: +25% critical hit damage. 15 - 25 meters: +10% critical hit damage and +10% critical hit chance. 25 meters+: 25% critical hit chance. An ally can receive all 3 damage buffs at the same time, but only ever of 1 type.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "Coyotes Mask",
  },
  {
    name: "Toxic Delivery",
    piece: "Mask",
    type: "Status",
    descriptionPVE:
      "Status effects also apply a damage over time debuff for 10 seconds. Total damage dealt is equal to 50% of your concussion grenade damage and increased by your status effect attributes.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "YES",
    exoticItem: "Vile",
  },
  {
    name: "Energize",
    piece: "Backpack",
    type: "Heal & Support",
    descriptionPVE:
      "Using an armor kit grants +1 skill tier for 15s. If already at skill tier 6, grants overcharge. Cooldown: 60s.",
    descriptionPVP: "",
    isNamed: "NO",
    namedItem: "",
    isExotic: "NO",
    exoticItem: "",
  },
];
