function timestamp() {
  const stamp =
    Date.now() - Math.floor(Math.random() * 1000 * 60 * 60 * 24 * 30);
  return new Date(stamp).toISOString();
}

export const rifleDbModel = "Rifle";

export const rifles = [
  {
    class: "RIFLE",
    family: "1886",
    model: "1886",
    modSlots: 1,
    magazineSize: 5,
    rpm: 100,
    accuracy: 399,
    stability: 752,
    optimalRange: 28,
    maxRange: 80,
    reloadSpeed: 3250,
    reloadSpeedFromEmpty: 3550,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 342247,
    damageWt5: 75828,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "1886",
    model: "The Virginian",
    modSlots: 1,
    magazineSize: 5,
    rpm: 100,
    accuracy: 399,
    stability: 752,
    optimalRange: 28,
    maxRange: 80,
    reloadSpeed: 3250,
    reloadSpeedFromEmpty: 3550,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 342247,
    damageWt5: 75828,
    notes:
      "Talent: Perfect Boomerang. Critical hits have a 75% chance to return the bullet to the magazine. If a bullet is returned to the magazine, the next shot has 50% increased damage.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "1886",
    model: "Diamondback",
    modSlots: 0,
    magazineSize: 5,
    rpm: 100,
    accuracy: 399,
    stability: 752,
    optimalRange: 28,
    maxRange: 80,
    reloadSpeed: 3250,
    reloadSpeedFromEmpty: 3550,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 342247,
    damageWt5: 75828,
    notes:
      "Talent: Agonizing Bite. Diamondback randomly marks an enemy. Hitting that enemy consumes the mark, guaranteeing a critical hit with damage amplified by 20%. After hitting a mark, all shots fired are guaranteed critical hits for 5 seconds. A new random enemy is marked afterwards and whenever you reload.",
    isNamed: "NO",
    isExotic: "YES",
  },
  {
    class: "RIFLE",
    family: "ACR",
    model: "ACR SS",
    modSlots: 4,
    magazineSize: 30,
    rpm: 420,
    accuracy: 740,
    stability: 575,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 2000,
    reloadSpeedFromEmpty: 2420,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 92614,
    damageWt5: 205200,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "AK-M",
    model: "Merciless",
    modSlots: 0,
    magazineSize: 50,
    rpm: 260,
    accuracy: 718,
    stability: 357,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 2200,
    reloadSpeedFromEmpty: 2620,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 84622,
    damageWt5: 18749,
    notes:
      "Talent: Binary Trigger. This weapon fires on trigger pull and release. If both bullets hit the same enemy, gain a stack. At 7 stacks, shooting an enemy deals +500% amplified damage and creates a 7 meter explosion dealing 500% weapon damage, consuming the stacks.",
    isNamed: "NO",
    isExotic: "YES",
  },
  {
    class: "RIFLE",
    family: "AK-M",
    model: "Ruthless",
    modSlots: 0,
    magazineSize: 50,
    rpm: 260,
    accuracy: 577,
    stability: 329,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 2200,
    reloadSpeedFromEmpty: 2620,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 84622,
    damageWt5: 18749,
    notes:
      "Talent: Binary Trigger. This weapon fires on trigger pull and release. If both bullets hit the same enemy, gain a stack. At 7 stacks, shooting an enemy deals +500% amplified damage and creates a 7 meter explosion dealing 500% weapon damage, consuming the stacks.",
    isNamed: "NO",
    isExotic: "YES",
  },
  {
    class: "RIFLE",
    family: "AR15",
    model: "UIC15 MOD2",
    modSlots: 4,
    magazineSize: 30,
    rpm: 240,
    accuracy: 723,
    stability: 783,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 1900,
    reloadSpeedFromEmpty: 2020,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 105777,
    damageWt5: 23436,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "Gilboa Snake",
    model: "Ravenous",
    modSlots: 0,
    magazineSize: 60,
    rpm: 240,
    accuracy: 0,
    stability: 0,
    optimalRange: 50,
    maxRange: 0,
    reloadSpeed: 210,
    reloadSpeedFromEmpty: 2520,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 122231,
    damageWt5: 27082,
    notes:
      "Talent: Geri and Freki. On trigger-pull, fire both barrels at once. When fired from the right shoulder, hits add offensive primers, and defensive primers when fired from the left shoulder. Hits from one shoulder will detonate all of the opposite shoulder's primers when present. When detonated, each offensive primer deals 75% weapon damage, while each defensive primer grants 2% bonus armor for 5 seconds. Primer effectiveness is doubled at 10 stacks.",
    isNamed: "NO",
    isExotic: "YES",
  },
  {
    class: "RIFLE",
    family: "M16A2",
    model: "M16A2",
    modSlots: 3,
    magazineSize: 30,
    rpm: 400,
    accuracy: 719,
    stability: 566,
    optimalRange: 32,
    maxRange: 105,
    reloadSpeed: 2100,
    reloadSpeedFromEmpty: 2600,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 84622,
    damageWt5: 18749,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "M16A2",
    model: "M16A2 Replica",
    modSlots: 3,
    magazineSize: 30,
    rpm: 400,
    accuracy: 719,
    stability: 566,
    optimalRange: 32,
    maxRange: 105,
    reloadSpeed: 2100,
    reloadSpeedFromEmpty: 2600,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 84622,
    damageWt5: 18749,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "M1A",
    model: "Classic M1A",
    modSlots: 3,
    magazineSize: 10,
    rpm: 180,
    accuracy: 485,
    stability: 591,
    optimalRange: 60,
    maxRange: 80,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3200,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 205442,
    damageWt5: 45518,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "M1A",
    model: "Bakers Dozen",
    modSlots: 3,
    magazineSize: 13,
    rpm: 180,
    accuracy: 485,
    stability: 591,
    optimalRange: 60,
    maxRange: 80,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3200,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 205442,
    damageWt5: 0,
    notes:
      "Talent: Perfect Lucky Shot. Magazine capacity is increased by 30%. Missed shots from cover have a 100% chance to return to the magazine.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "M1A",
    model: "M1A CQB",
    modSlots: 4,
    magazineSize: 10,
    rpm: 320,
    accuracy: 463,
    stability: 647,
    optimalRange: 60,
    maxRange: 80,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3200,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 156080,
    damageWt5: 34581,
    notes: "",
    isNamed: "",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "M1A",
    model: "M1A CQB Replica",
    modSlots: 4,
    magazineSize: 10,
    rpm: 320,
    accuracy: 463,
    stability: 647,
    optimalRange: 60,
    maxRange: 80,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3200,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 156080,
    damageWt5: 34581,
    notes: "",
    isNamed: "",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "M1A",
    model: "SOCOM M1A",
    modSlots: 4,
    magazineSize: 10,
    rpm: 320,
    accuracy: 484,
    stability: 619,
    optimalRange: 60,
    maxRange: 80,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3200,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 141036,
    damageWt5: 31248,
    notes: "",
    isNamed: "",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "M4",
    model: "Lightweight M4",
    modSlots: 4,
    magazineSize: 30,
    rpm: 360,
    accuracy: 665,
    stability: 459,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 2100,
    reloadSpeedFromEmpty: 2520,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 103897,
    damageWt5: 23019,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "M4",
    model: "LVOA-C",
    modSlots: 4,
    magazineSize: 30,
    rpm: 380,
    accuracy: 672,
    stability: 518,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 2100,
    reloadSpeedFromEmpty: 2520,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 100136,
    damageWt5: 22186,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "M4",
    model: "Surge",
    modSlots: 4,
    magazineSize: 30,
    rpm: 380,
    accuracy: 665,
    stability: 459,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 2100,
    reloadSpeedFromEmpty: 2520,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 100136,
    damageWt5: 0,
    notes:
      "Talent: Perfect Spike. Headshots grant 25% skill damage for 8 seconds.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "MDR",
    model: "Urban MDR",
    modSlots: 4,
    magazineSize: 20,
    rpm: 360,
    accuracy: 519,
    stability: 619,
    optimalRange: 28,
    maxRange: 80,
    reloadSpeed: 2200,
    reloadSpeedFromEmpty: 2020,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 97785,
    damageWt5: 21665,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "MDR",
    model: "Urban MDR Replica",
    modSlots: 4,
    magazineSize: 20,
    rpm: 360,
    accuracy: 519,
    stability: 619,
    optimalRange: 28,
    maxRange: 80,
    reloadSpeed: 2200,
    reloadSpeedFromEmpty: 2020,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 97785,
    damageWt5: 21665,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "MK47",
    model: "Resolute MK47",
    modSlots: 4,
    magazineSize: 30,
    rpm: 300,
    accuracy: 0,
    stability: 0,
    optimalRange: 60,
    maxRange: 0,
    reloadSpeed: 1970,
    reloadSpeedFromEmpty: 2500,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 104837,
    damageWt5: 0,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "MK47",
    model: "Harmony",
    modSlots: 4,
    magazineSize: 30,
    rpm: 300,
    accuracy: 0,
    stability: 0,
    optimalRange: 60,
    maxRange: 0,
    reloadSpeed: 1970,
    reloadSpeedFromEmpty: 2500,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 104837,
    damageWt5: 0,
    notes:
      "Talent: Perfectly in Sync. Hitting an enemy grants +20% skill damage for 5 seconds. Using a skill or damaging an enemy with a skill grants +20% weapon damage for 5 seconds. Damage increases are doubled while both buffs are active at the same time.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "SCAR",
    model: "Military MK17",
    modSlots: 4,
    magazineSize: 20,
    rpm: 275,
    accuracy: 490,
    stability: 666,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 1900,
    reloadSpeedFromEmpty: 2320,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 116120,
    damageWt5: 25728,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "SCAR",
    model: "Police MK17",
    modSlots: 4,
    magazineSize: 20,
    rpm: 275,
    accuracy: 0,
    stability: 0,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 1900,
    reloadSpeedFromEmpty: 2320,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 116120,
    damageWt5: 25728,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "SCAR",
    model: "Police MK17 Replica",
    modSlots: 4,
    magazineSize: 20,
    rpm: 275,
    accuracy: 0,
    stability: 0,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 1900,
    reloadSpeedFromEmpty: 2320,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 116120,
    damageWt5: 25728,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "SCAR",
    model: "Everlasting Gaze",
    modSlots: 4,
    magazineSize: 20,
    rpm: 275,
    accuracy: 490,
    stability: 666,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 1900,
    reloadSpeedFromEmpty: 2320,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 116120,
    damageWt5: 25728,
    notes:
      "Talent: Perfect Perpetuation. Headshots grant 50% status effect damage and duration to the next status effect you apply. Cooldown is 16 seconds.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "SIG 716",
    model: "SIG 716",
    modSlots: 4,
    magazineSize: 20,
    rpm: 320,
    accuracy: 514,
    stability: 609,
    optimalRange: 60,
    maxRange: 80,
    reloadSpeed: 2100,
    reloadSpeedFromEmpty: 2600,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 97785,
    damageWt5: 21665,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "SIG 716",
    model: "SIG 716 CQB",
    modSlots: 3,
    magazineSize: 20,
    rpm: 320,
    accuracy: 510,
    stability: 635,
    optimalRange: 60,
    maxRange: 80,
    reloadSpeed: 2100,
    reloadSpeedFromEmpty: 2600,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 99665,
    damageWt5: 22082,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "SIG 716",
    model: "SIG 716 Replica",
    modSlots: 4,
    magazineSize: 20,
    rpm: 320,
    accuracy: 514,
    stability: 609,
    optimalRange: 60,
    maxRange: 80,
    reloadSpeed: 2100,
    reloadSpeedFromEmpty: 2600,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 97785,
    damageWt5: 21665,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "SIG 716",
    model: "Artist's Tool",
    modSlots: 3,
    magazineSize: 20,
    rpm: 320,
    accuracy: 510,
    stability: 635,
    optimalRange: 60,
    maxRange: 80,
    reloadSpeed: 2100,
    reloadSpeedFromEmpty: 2600,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 99665,
    damageWt5: 22082,
    notes:
      "Talent: Perfect Rifleman. Landing headshots adds a stack of bonus 11% weapon damage for 5 seconds. Max stack is 6. Additional headshots refresh the duration.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "UMP-45",
    model: "USC .45 ACP",
    modSlots: 4,
    magazineSize: 20,
    rpm: 420,
    accuracy: 419,
    stability: 556,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 2000,
    reloadSpeedFromEmpty: 2420,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 98255,
    damageWt5: 21769,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "RIFLE",
    family: "UMP-45",
    model: "USC .45 ACP Replica",
    modSlots: 4,
    magazineSize: 20,
    rpm: 420,
    accuracy: 419,
    stability: 556,
    optimalRange: 50,
    maxRange: 80,
    reloadSpeed: 2000,
    reloadSpeedFromEmpty: 2420,
    headshotMultiplier: 160,
    weaponBonusType: "CHD",
    maxBonusValue: 17,
    damageLevel40: 98255,
    damageWt5: 21769,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
];
