function timestamp() {
  const stamp =
    Date.now() - Math.floor(Math.random() * 1000 * 60 * 60 * 24 * 30);
  return new Date(stamp).toISOString();
}

export const brands = [
  {
    name: "5.11 Tactical",
    setBonusOne: "10% Health",
    setBonusTwo: "20% Extra Incoming Healing",
    setBonusThree: "10% Hazard Protection",
    armourTalent: "",
  },
  {
    name: "Airaldi Holdings",
    setBonusOne: "10% Marksman Rifle Damage",
    setBonusTwo: "15% Headshot Damage",
    setBonusThree: "5% Damage to Armour",
    armourTalent: "",
  },
  {
    name: "Alps Summit Armaments",
    setBonusOne: "20% Skill Repair",
    setBonusTwo: "20% Skill Duration",
    setBonusThree: "10% Skill Haste",
    armourTalent: "",
  },
  {
    name: "Badger Tuff",
    setBonusOne: "10% Shotgun Damage",
    setBonusTwo: "5% Total Armour",
    setBonusThree: "10% Armour on kill",
    armourTalent: "",
  },
  {
    name: "Belstone Armory",
    setBonusOne: "1% Armour Regeneration",
    setBonusTwo: "10% Armour on kill",
    setBonusThree: "20% Incoming Repairs",
    armourTalent: "",
  },
  {
    name: "Ceska Vyroba s.r.o",
    setBonusOne: "10% Critical Hit Chance",
    setBonusTwo: "10% Hazard Protection",
    setBonusThree: "10% Health",
    armourTalent: "",
  },
  {
    name: "China Light Industries Corporation",
    setBonusOne: "15% Explosive Damage",
    setBonusTwo: "10% Skill Haste",
    setBonusThree: "10% Status Effects",
    armourTalent: "",
  },
  {
    name: "Douglas & Harding",
    setBonusOne: "20% Pistol Damage",
    setBonusTwo: "20% Stability",
    setBonusThree: "20% Accuracy",
    armourTalent: "",
  },
  {
    name: "Empress International",
    setBonusOne: "10% Skill Health",
    setBonusTwo: "10% Skill Damage",
    setBonusThree: "10% Skill Efficiency",
  },
  {
    name: "Fenris Group AB",
    setBonusOne: "10% Assault Rifle Damage",
    setBonusTwo: "20% Reload Speed",
    setBonusThree: "20% Stability",
    armourTalent: "",
  },
  {
    name: "Gila Guard",
    setBonusOne: "5% Total Armour",
    setBonusTwo: "10% Health",
    setBonusThree: "1% Armour Regeneration per second",
    armourTalent: "",
  },
  {
    name: "Golan Gear Ltd",
    setBonusOne: "10% Status Effects",
    setBonusTwo: "1% Armour Regeneration per second",
    setBonusThree: "5% Total Armour",
    armourTalent: "",
  },
  {
    name: "Grupo Sombra S.A",
    setBonusOne: "15% Critical Hit Damage",
    setBonusTwo: "15% Explosive Damage",
    setBonusThree: "15% Headshot Damage",
    armourTalent: "",
  },
  {
    name: "Hana-U Corporation",
    setBonusOne: "10% Skill Haste",
    setBonusTwo: "10% Skill Damage",
    setBonusThree: "5% Weapon Damage",
    armourTalent: "",
  },
  {
    name: "Murakami Industries",
    setBonusOne: "20% Skill Duration",
    setBonusTwo: "20% Skill Repair",
    setBonusThree: "10% Skill Damage",
    armourTalent: "",
  },
  {
    name: "Overlord Armaments",
    setBonusOne: "10% Rifle Damage",
    setBonusTwo: "20% Accuracy",
    setBonusThree: "10% Weapon Handling",
    armourTalent: "",
  },
  {
    name: "Petrov Defense Group",
    setBonusOne: "10% Light Machine Gun Damage",
    setBonusTwo: "10% Weapon Handling",
    setBonusThree: "20% Ammunition Capacity",
    armourTalent: "",
  },
  {
    name: "Providence Defense",
    setBonusOne: "15% Headshot Damage",
    setBonusTwo: "10% Critical Hit Chance",
    setBonusThree: "15% Critical Hit Damage",
    armourTalent: "",
  },
  {
    name: "Richter & Kaiser GmbH",
    setBonusOne: "20% Extra Incoming Healing",
    setBonusTwo: "10% Explosive Resistance",
    setBonusThree: "20% Skill Repair",
    armourTalent: "",
  },
  {
    name: "Sokolov Concern",
    setBonusOne: "10% SMG Damage",
    setBonusTwo: "15% Critical Hit Damage",
    setBonusThree: "10% Critical Hit Chance",
    armourTalent: "",
  },
  {
    name: "Walker, Harris & Co.",
    setBonusOne: "5% Weapon Damage",
    setBonusTwo: "5% Damage to Armour",
    setBonusThree: "5% Damage to Health",
    armourTalent: "",
  },
  {
    name: "Wyvern Wear",
    setBonusOne: "10% Skill Damage",
    setBonusTwo: "10% Status Effects",
    setBonusThree: "20% Skill Duration",
    armourTalent: "",
  },
  {
    name: "Yaahl Gear",
    setBonusOne: "10% Hazard Protection",
    setBonusTwo: "5% Weapon Damage",
    setBonusThree: "40% Pulse Resistance",
    armourTalent: "",
  },
  {
    name: "Improvised",
    setBonusOne: "",
    setBonusTwo: "",
    setBonusThree: "",
    armourTalent: "",
  },
  {
    name: "All Brands",
    setBonusOne: "",
    setBonusTwo: "",
    setBonusThree: "",
    armourTalent: "",
  },
];
