function timestamp() {
  const stamp =
    Date.now() - Math.floor(Math.random() * 1000 * 60 * 60 * 24 * 30);
  return new Date(stamp).toISOString();
}

export const lmgDbModel = "LightMachineGun";

export const lightMachineGuns = [
  {
    class: "LIGHT MACHINE GUN",
    family: "KAC",
    model: "Stoner LAMG",
    modSlots: 4,
    magazineSize: 200,
    rpm: 580,
    accuracy: 0,
    stability: 0,
    optimalRange: 40,
    maxRange: 80,
    reloadSpeed: 4670,
    reloadSpeedFromEmpty: 4670,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 47952,
    damageWt5: 10624,
    notes: "Fixed barrel mod",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "KAC",
    model: "Quiet Roar",
    modSlots: 4,
    magazineSize: 200,
    rpm: 580,
    accuracy: 0,
    stability: 0,
    optimalRange: 40,
    maxRange: 80,
    reloadSpeed: 4670,
    reloadSpeedFromEmpty: 4670,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 47952,
    damageWt5: 0,
    notes:
      "Fixed barrel mod. Talent: Perfect Overwhelm. Suppressing an enemy, that is not currently suppressed, grants 12% weapon damage for 12 seconds. Max stack is 4.",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "L86",
    model: "Custom L86 A2",
    modSlots: 4,
    magazineSize: 30,
    rpm: 610,
    accuracy: 297,
    stability: 738,
    optimalRange: 32,
    maxRange: 105,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3250,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 59705,
    damageWt5: 13228,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "L86",
    model: "Custom L86 A2 Replica",
    modSlots: 4,
    magazineSize: 30,
    rpm: 610,
    accuracy: 297,
    stability: 738,
    optimalRange: 32,
    maxRange: 105,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3250,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 59705,
    damageWt5: 13228,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "L86",
    model: "Military L86 LSW",
    modSlots: 4,
    magazineSize: 30,
    rpm: 610,
    accuracy: 307,
    stability: 746,
    optimalRange: 32,
    maxRange: 105,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3250,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 59705,
    damageWt5: 13228,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "L86",
    model: "Tabula Rasa",
    modSlots: 4,
    magazineSize: 30,
    rpm: 610,
    accuracy: 307,
    stability: 746,
    optimalRange: 32,
    maxRange: 105,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3250,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 59705,
    damageWt5: 13228,
    notes:
      "Talent: Perfectly Steady Handed. Hits grant a stack of 1% accuracy and stability. At 75 stacks, consumes them to refill the magazine.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M249",
    model: "M249 B",
    modSlots: 4,
    magazineSize: 100,
    rpm: 550,
    accuracy: 327,
    stability: 736,
    optimalRange: 35,
    maxRange: 100,
    reloadSpeed: 5600,
    reloadSpeedFromEmpty: 5850,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 56414,
    damageWt5: 12499,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M249",
    model: "Black Friday",
    modSlots: 4,
    magazineSize: 100,
    rpm: 550,
    accuracy: 327,
    stability: 736,
    optimalRange: 35,
    maxRange: 100,
    reloadSpeed: 5600,
    reloadSpeedFromEmpty: 5850,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 56414,
    damageWt5: 12499,
    notes:
      "Talent: Perfectly Unhinged. Receive 22% weapon damage at the cost of 25% stability and 25% accuracy.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M249",
    model: "The Stinger",
    modSlots: 4,
    magazineSize: 100,
    rpm: 550,
    accuracy: 327,
    stability: 736,
    optimalRange: 35,
    maxRange: 100,
    reloadSpeed: 5600,
    reloadSpeedFromEmpty: 5850,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 56414,
    damageWt5: 12499,
    notes:
      "Talent: Swift. Performing a cover-to-cover move grants +20% weapon damage for 15s",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M249",
    model: "Military MK46",
    modSlots: 4,
    magazineSize: 100,
    rpm: 550,
    accuracy: 301,
    stability: 759,
    optimalRange: 35,
    maxRange: 100,
    reloadSpeed: 5600,
    reloadSpeedFromEmpty: 5850,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 56414,
    damageWt5: 12499,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M249",
    model: "Military MK46 Replica",
    modSlots: 4,
    magazineSize: 100,
    rpm: 550,
    accuracy: 301,
    stability: 759,
    optimalRange: 35,
    maxRange: 100,
    reloadSpeed: 5600,
    reloadSpeedFromEmpty: 5850,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 56414,
    damageWt5: 12499,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M249",
    model: "Pestilence",
    modSlots: 0,
    magazineSize: 100,
    rpm: 550,
    accuracy: 208,
    stability: 383,
    optimalRange: 35,
    maxRange: 100,
    reloadSpeed: 5600,
    reloadSpeedFromEmpty: 5850,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 47012,
    damageWt5: 10416,
    notes:
      "Talent: Plague of the Outcasts. Hits apply a debuff dealing 100% weapon damage over 10 seconds. This stacks up to 50 times. Whenever an enemy dies with this debuff, all stacks are transferred to a nearby enemy within 25 meters.",
    isNamed: "NO",
    isExotic: "YES",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M249",
    model: "Tactical M249 Para",
    modSlots: 4,
    magazineSize: 100,
    rpm: 550,
    accuracy: 0,
    stability: 0,
    optimalRange: 35,
    maxRange: 100,
    reloadSpeed: 5600,
    reloadSpeedFromEmpty: 5850,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 56414,
    damageWt5: 12499,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M60",
    model: "Black Market M60 E6",
    modSlots: 4,
    magazineSize: 100,
    rpm: 500,
    accuracy: 208,
    stability: 775,
    optimalRange: 40,
    maxRange: 80,
    reloadSpeed: 5500,
    reloadSpeedFromEmpty: 6050,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 61116,
    damageWt5: 13541,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M60",
    model: "Black Market M60 E6 Replica",
    modSlots: 4,
    magazineSize: 100,
    rpm: 500,
    accuracy: 208,
    stability: 775,
    optimalRange: 40,
    maxRange: 80,
    reloadSpeed: 5500,
    reloadSpeedFromEmpty: 6050,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 61116,
    damageWt5: 13541,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M60",
    model: "Good Times",
    modSlots: 4,
    magazineSize: 100,
    rpm: 500,
    accuracy: 225,
    stability: 742,
    optimalRange: 40,
    maxRange: 80,
    reloadSpeed: 5500,
    reloadSpeedFromEmpty: 6050,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 61116,
    damageWt5: 0,
    notes:
      "Talent: Perfect Fast Hands. Critical hits add a stack of 8% reload speed bonus. Max stack is 40.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M60",
    model: "Classic M60",
    modSlots: 3,
    magazineSize: 100,
    rpm: 500,
    accuracy: 225,
    stability: 742,
    optimalRange: 40,
    maxRange: 80,
    reloadSpeed: 5500,
    reloadSpeedFromEmpty: 6050,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 63466,
    damageWt5: 14062,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M60",
    model: "Classic M60 Replica",
    modSlots: 3,
    magazineSize: 100,
    rpm: 500,
    accuracy: 225,
    stability: 742,
    optimalRange: 40,
    maxRange: 80,
    reloadSpeed: 5500,
    reloadSpeedFromEmpty: 6050,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 63466,
    damageWt5: 14062,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "M60",
    model: "Military M60 E4",
    modSlots: 4,
    magazineSize: 100,
    rpm: 500,
    accuracy: 225,
    stability: 758,
    optimalRange: 40,
    maxRange: 80,
    reloadSpeed: 5500,
    reloadSpeedFromEmpty: 6050,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 61116,
    damageWt5: 13541,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "MG5",
    model: "Infantry MG5",
    modSlots: 4,
    magazineSize: 50,
    rpm: 800,
    accuracy: 311,
    stability: 671,
    optimalRange: 30,
    maxRange: 105,
    reloadSpeed: 5600,
    reloadSpeedFromEmpty: 5800,
    headshotMultiplier: 185,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 43251,
    damageWt5: 9583,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "MG5",
    model: "Infantry MG5 Replica",
    modSlots: 4,
    magazineSize: 50,
    rpm: 800,
    accuracy: 311,
    stability: 671,
    optimalRange: 30,
    maxRange: 105,
    reloadSpeed: 5600,
    reloadSpeedFromEmpty: 5800,
    headshotMultiplier: 185,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 43251,
    damageWt5: 9583,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "MG5",
    model: "MG5",
    modSlots: 3,
    magazineSize: 50,
    rpm: 800,
    accuracy: 273,
    stability: 652,
    optimalRange: 30,
    maxRange: 105,
    reloadSpeed: 5600,
    reloadSpeedFromEmpty: 5800,
    headshotMultiplier: 185,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 44661,
    damageWt5: 9895,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "MG5",
    model: "Sleipner",
    modSlots: 3,
    magazineSize: 50,
    rpm: 800,
    accuracy: 273,
    stability: 652,
    optimalRange: 30,
    maxRange: 105,
    reloadSpeed: 5600,
    reloadSpeedFromEmpty: 5800,
    headshotMultiplier: 185,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 44661,
    damageWt5: 9895,
    notes:
      "Talent: Perfect Frenzy. For every 8 bullets in the magazine capacity, gain 3% rate of fire and 3% weapon damage for 5 seconds when reloading from empty.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "NEGEV",
    model: "IWI NEGEV",
    modSlots: 4,
    magazineSize: 100,
    rpm: 850,
    accuracy: 225,
    stability: 0,
    optimalRange: 40,
    maxRange: 80,
    reloadSpeed: 4300,
    reloadSpeedFromEmpty: 6050,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 37610,
    damageWt5: 0,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "NEGEV",
    model: "Carnage",
    modSlots: 4,
    magazineSize: 100,
    rpm: 850,
    accuracy: 225,
    stability: 0,
    optimalRange: 40,
    maxRange: 80,
    reloadSpeed: 4300,
    reloadSpeedFromEmpty: 6050,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 37610,
    damageWt5: 0,
    notes:
      "Talent: Perfect Sadist. Deal +25% weapon damage to bleeding enemies. After 3 kills, applies bleed to the next enemy you hit.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "NEGEV",
    model: "Bullet King",
    modSlots: 0,
    magazineSize: 1000,
    rpm: 850,
    accuracy: 225,
    stability: 0,
    optimalRange: 40,
    maxRange: 80,
    reloadSpeed: 4300,
    reloadSpeedFromEmpty: 6050,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 37610,
    damageWt5: 0,
    notes:
      "Talent: Bullet Hell. This weapon never needs to be reloaded. For every 100 bullets that hit an enemy, replenish some ammo to you and your allies' reserves.",
    isNamed: "NO",
    isExotic: "YES",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "RPK-74",
    model: "Black Market RPK-74 E",
    modSlots: 4,
    magazineSize: 45,
    rpm: 650,
    accuracy: 276,
    stability: 764,
    optimalRange: 28,
    maxRange: 105,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3250,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 55474,
    damageWt5: 12291,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "RPK-74",
    model: "Black Market RPK-74 E Replica",
    modSlots: 4,
    magazineSize: 45,
    rpm: 650,
    accuracy: 276,
    stability: 764,
    optimalRange: 28,
    maxRange: 105,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3250,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 55474,
    damageWt5: 12291,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "RPK-74",
    model: "New Reliable",
    modSlots: 4,
    magazineSize: 45,
    rpm: 650,
    accuracy: 276,
    stability: 764,
    optimalRange: 28,
    maxRange: 105,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3250,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 55474,
    damageWt5: 0,
    notes: "Talent: Perfectly Optimized. Increase weapon handling by 30%.",
    isNamed: "YES",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "RPK-74",
    model: "Classic RPK-74",
    modSlots: 4,
    magazineSize: 45,
    rpm: 650,
    accuracy: 293,
    stability: 732,
    optimalRange: 28,
    maxRange: 105,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3250,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 55474,
    damageWt5: 12291,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
  {
    class: "LIGHT MACHINE GUN",
    family: "RPK-74",
    model: "Military RPK-74 M",
    modSlots: 4,
    magazineSize: 45,
    rpm: 650,
    accuracy: 294,
    stability: 748,
    optimalRange: 28,
    maxRange: 105,
    reloadSpeed: 2500,
    reloadSpeedFromEmpty: 3250,
    headshotMultiplier: 165,
    weaponBonusType: "OOC",
    maxBonusValue: 12,
    damageLevel40: 55474,
    damageWt5: 12291,
    notes: "",
    isNamed: "NO",
    isExotic: "NO",
  },
];
